2024-08-08 15:55:53.976831	[error]HTTPSConnectionPool(host='baboonassociation.pythonanywhere.com', port=443): Max retries exceeded with url: /versions/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001AFD38CF990>: Failed to resolve 'baboonassociation.pythonanywhere.com' ([Errno 11001] getaddrinfo failed)"))2024-08-08 15:56:16.269905	[error]HTTPSConnectionPool(host='baboonassociation.pythonanywhere.com', port=443): Max retries exceeded with url: /versions/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001AFD3B12650>: Failed to resolve 'baboonassociation.pythonanywhere.com' ([Errno 11001] getaddrinfo failed)"))